version: '3.8'

services:
  # Spring Boot приложение (подключается к внешней БД)
  app:
    build: .
    container_name: mapmaker-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/mapmaker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - GOOGLE_API_KEY=AIzaSyALDVyBHf9Uu6TL64_IW1VE6Gn7pRvHHC4
      # Переменные для DatabaseHelper
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=mapmaker
      - DB_USER=postgres
      - DB_PASSWORD=1234
    volumes:
      - ./maps:/app/maps:ro
      - ./data:/app/data
    networks:
      - mapmaker-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - nginx

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: mapmaker-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "8081:80"
      - "443:443"
    networks:
      - mapmaker-network
    restart: unless-stopped

networks:
  mapmaker-network:
    driver: bridge 