version: '3.8'

services:
  mapmaker-local:
    build:
      context: .
      dockerfile: Dockerfile-local
    container_name: mapmaker-local
    ports:
      - "8080:8080"
    environment:
      # Базовые настройки Spring
      - SPRING_PROFILES_ACTIVE=docker
      
      # Настройки БД (внешняя PostgreSQL)
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=mapmaker
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      
      # Локальный GraphHopper для Витебской области
      - routing.mode=local
      - spring.profiles.active=local-graphhopper
      - graphhopper.osm.file=/app/maps/vitebskaya.pbf
      - graphhopper.graph.location=/app/data/graphhopper-cache
      
      # Java опции для больших карт
      - JAVA_OPTS=-Xmx6g -Xms4g -XX:+UseG1GC
      
      # API ключи (оставляем для fallback)
      - google.maps.api.key=${GOOGLE_MAPS_API_KEY:-AIzaSyBQwvM_w_zjXN6uPdanOsbrAsSKkcbNX9M}
      - graphhopper.api.key=${GRAPHHOPPER_API_KEY:-3ed70bc6-d2bc-4816-851f-a2ef0bb4c563}
    
    volumes:
      # Том для кэша GraphHopper (важно для сохранения обработанных данных)
      - graphhopper_cache:/app/data
      # Том для карт OSM
      - ./maps:/app/maps
      # Логи
      - ./logs:/app/logs
    
    networks:
      - mapmaker-network
    
    # Ресурсы для обработки больших карт
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    
    # Увеличиваем время запуска (первый импорт может занять много времени)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 300s

  nginx:
    image: nginx:alpine
    container_name: mapmaker-nginx-local
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mapmaker-local
    networks:
      - mapmaker-network

volumes:
  graphhopper_cache:
    driver: local

networks:
  mapmaker-network:
    driver: bridge 